### ISSUE TITLE
Help converting RcDoc into Arena

### ISSUE THREAD

**Issue by chenyan2002** [Marwes/pretty.rs#64] opened 2020-08-15 22:36 UTC
I have a function that returns `RcDoc<()>`. Is there a way to append this into an Arena allocated doc? In general, I would like to know if different doc types can be converted to each other, e.g. conversion between `BoxDoc`, `RcDoc`, `RefDoc`, `DocBuilder` etc.

```
let arena = Arena::<()>::new();
let doc = arena.text(header);
let rcdoc : RcDoc = f();
doc.append(rcdoc);
    ^^^^^^ the trait `std::convert::From<pretty::Doc<'_, pretty::RcDoc<'_>>>` is not implemented for `std::borrow::Cow<'_, str>`
```

**Comment by Marwes** [comment] 2020-08-16 09:08
There isn't a way to convert the doc types between each other as is, I just expected that a single doc type would be used pervasively.

I guess there could be a conversion function added like

```rust
fn convert_doc<A>(allocator: &A, doc: &Doc) -> Doc<A>
    where A: DocAllocator
```

But it would have to traverse and re-allocate the entire document so it still wouldn't be efficient.

If you do need to use different doc types my first recommendation would be to parameterize the function hover a `DocAllocator` so that you can call the function to create `RcDoc` or `RefDoc`

**Comment by chenyan2002** [comment] 2020-08-16 22:41
Thanks for the suggestion! Yeah, there is not much documentation on the `DocAllocator`, and I only find out this use after reading the `gluon` code :)

The doc uses `RcDoc` in the quick start, that's where I start building libraries around it. It works great, until I need borrow locally created variables and run into lifetime issues.

**Comment by Marwes** [comment] 2020-08-17 08:10
> It works great, until I need borrow locally created variables and run into lifetime issues.

Might that be the same as https://github.com/Marwes/pretty.rs/issues/58 ?

**Comment by chenyan2002** [comment] 2020-08-19 04:11
Yeah, sounds like the same issue. Thanks for the pointer!

**Comment by Marwes** [comment] 2022-05-12 13:22
Sounds like this is a duplicate of #58 now. Closing.

**Closed by Marwes** 2022-05-12 13:22 UTC
